---
services:
  traefik:
    volumes:
      - ./traefik/traefik.dev.yml:/etc/traefik/traefik.yml:ro
      - ./traefik/config:/etc/traefik/config:ro
      - ./traefik/config/certs:/etc/traefik/certs:ro
    extra_hosts:
      - "staging-grimwaves.duckdns.org:127.0.0.1"

  api:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`staging-grimwaves.duckdns.org`)"
      - "traefik.http.routers.api.entrypoints=websecure"
      - "traefik.http.services.api.loadbalancer.server.port=8000"
      - "traefik.http.routers.api.tls=true"
      - "traefik.http.routers.api.tls.domains[0].main=staging-grimwaves.duckdns.org"
      - "traefik.http.routers.api-http.rule=Host(`staging-grimwaves.duckdns.org`)"
      - "traefik.http.routers.api-http.entrypoints=web"
      - "traefik.http.routers.api-http.service=api@docker"
    environment:
      - GRIMWAVES_CELERY_BROKER_URL=redis://redis:6379/0
      - GRIMWAVES_CELERY_RESULT_BACKEND=redis://redis:6379/0
      - GRIMWAVES_REDIS_URL=redis://redis:6379/1
    volumes:  
      - ./data:/app/data:ro
      - /mnt/data/logs:/app/logs
      - ./vault-agent/sockets:/vault-agent/sockets
      - ./vault-agent/rendered:/vault-agent/rendered:ro

  redis:
    image: redis:7.4.3-alpine
    ports:
      - "6379:6379"
    volumes:
      - /mnt/data/redis:/data
    command: redis-server --appendonly yes

  celery-worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A grimwaves_api.core.celery_app worker --loglevel=info
    volumes:
      - ./data:/app/data:ro
      - /mnt/data/logs:/app/logs
      - ./vault-agent/rendered:/vault-agent/rendered:ro
    environment:
      - SETTINGS_ENV_FILE=/vault-agent/rendered/.env
      - GRIMWAVES_CELERY_BROKER_URL=redis://redis:6379/0
      - GRIMWAVES_CELERY_RESULT_BACKEND=redis://redis:6379/0
      - GRIMWAVES_REDIS_URL=redis://redis:6379/1
    depends_on:
      - redis
