---
services:
  vault-agent:
    container_name: vault-agent-e2e
    networks:
      - grimwaves-e2e-network

  traefik:
    container_name: grimwaves-traefik-e2e
    volumes:
      - ./traefik/traefik.dev.yml:/etc/traefik/traefik.yml:ro  # Override config for E2E
      - ./traefik/config:/etc/traefik/config:ro
      - ./traefik/config/certs:/etc/traefik/certs:ro
    networks:
      - grimwaves-e2e-network
    extra_hosts:
      - "api.grimwaves.local:127.0.0.1"
      - "grimwaves.local:127.0.0.1"
      - "health.local:127.0.0.1"

  api:
    container_name: grimwaves-api-e2e
    networks:
      - grimwaves-e2e-network
    ports:
      - "8000:8000" # Expose API port directly for E2E tests

  redis:
    container_name: grimwaves-redis-e2e
    networks:
      - grimwaves-e2e-network

  celery-worker:
    container_name: grimwaves-celery-worker-e2e
    networks:
      - grimwaves-e2e-network

networks:
  grimwaves-e2e-network:
    name: grimwaves-e2e-network
    driver: bridge

