---
services:
  traefik:
    volumes:
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./traefik/config:/etc/traefik/config:ro
      - ./traefik/acme.json:/etc/traefik/acme.json
    environment:
      - DUCKDNS_TOKEN=${DUCKDNS_TOKEN:-dummy_token}
      - DUCKDNS_DOMAIN=${DUCKDNS_DOMAIN:-grimwaves.duckdns.org}
      - ENVIRONMENT=production
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`traefik.${DUCKDNS_DOMAIN:-grimwaves.duckdns.org}`)"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.entrypoints=websecure"
      - "traefik.http.routers.dashboard.tls.certresolver=duckdns"
      - "traefik.http.routers.dashboard.middlewares=auth@file"
    extra_hosts:
      - "${DUCKDNS_DOMAIN:-grimwaves.duckdns.org}:127.0.0.1"

  api:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`${DUCKDNS_DOMAIN:-grimwaves.duckdns.org}`)"
      - "traefik.http.routers.api.entrypoints=websecure"
      - "traefik.http.routers.api.tls.certresolver=duckdns"
      - "traefik.http.services.api.loadbalancer.server.port=8000"
      - "traefik.http.routers.api-http.rule=Host(`${DUCKDNS_DOMAIN:-grimwaves.duckdns.org}`)"
      - "traefik.http.routers.api-http.entrypoints=web"
      - "traefik.http.routers.api-http.service=api@docker"
      - "traefik.http.routers.api-http.middlewares=redirect-to-https@file"
    environment:
      - ENVIRONMENT=production
      - DEBUG=false
      - GRIMWAVES_CELERY_BROKER_URL=redis://redis:6379/0
      - GRIMWAVES_CELERY_RESULT_BACKEND=redis://redis:6379/0
      - GRIMWAVES_REDIS_URL=redis://redis:6379/1
    volumes:
      - ./data:/app/data:ro
      - /mnt/data/logs:/app/logs
      - ./vault-agent/sockets:/vault-agent/sockets
      - ./vault-agent/rendered:/vault-agent/rendered:ro

  redis:
    image: redis:7.4.3-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes

  celery-worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A grimwaves_api.core.celery_app worker --loglevel=info
    volumes:
      - ./data:/app/data:ro
      - /mnt/data/logs:/app/logs
      - ./vault-agent/rendered:/vault-agent/rendered:ro
    environment:
      - SETTINGS_ENV_FILE=/vault-agent/rendered/.env
      - ENVIRONMENT=production
      - DEBUG=false
      - GRIMWAVES_CELERY_BROKER_URL=redis://redis:6379/0
      - GRIMWAVES_CELERY_RESULT_BACKEND=redis://redis:6379/0
      - GRIMWAVES_REDIS_URL=redis://redis:6379/1
    restart: unless-stopped
    depends_on:
      - redis
      - api

# Don't define volumes here - use bind mounts to DigitalOcean Volume
# The base redis-data volume from docker-compose.yml will be ignored

# No networks section - using network configuration from base docker-compose.yml
# No volumes section - using bind mounts to DigitalOcean Volume

